name: Test Workflow

on:
  pull_request:
    branches:
      - "**"

jobs:
  test_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Go setup
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.0'

      - name: Run Test
        run: |
          make test
